In [1]:
import numpy as np
from sentence_transformers import SentenceTransformer

D:\study\learning-python\back-end\talk-to-django\venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [2]:
# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

D:\study\learning-python\back-end\talk-to-django\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
## this is the index representation of the words we want the number representation
split_docs = sorted(["The dog jumped over the cat"][0].split(' '))
split_docs

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [6]:
docs = ["The dog jumped over the cat"]
docs

['The dog jumped over the cat']

In [10]:
## this way we make a number representaion of the list docs that is numpy array
embeddings = model.encode(docs, clean_up_tokenization_spaces=False)
embeddings

array([[ 5.44742756e-02,  3.71413566e-02,  7.23646879e-02,
         7.01894835e-02, -5.60807297e-03, -2.30735517e-03,
        -3.77298556e-02,  1.51365120e-02,  9.50729940e-03,
        -3.03878740e-04,  5.88888414e-02,  2.10996270e-02,
         6.14684308e-03, -6.37330860e-02,  1.38773452e-02,
        -9.31993593e-03, -1.19946703e-01, -2.11697072e-03,
         6.35646209e-02, -2.08781026e-02, -2.80396361e-02,
        -3.85088623e-02,  2.66364682e-03, -5.36900423e-02,
        -2.24582162e-02,  4.27320674e-02, -6.99243620e-02,
        -6.33601025e-02,  1.81462858e-02, -1.30238328e-02,
        -1.66832563e-02, -1.05505204e-02, -3.54123898e-02,
         5.32195866e-02, -6.18179962e-02, -6.84991181e-02,
         6.55241832e-02, -1.77633934e-04,  4.45996523e-02,
         1.20984331e-01, -4.50547561e-02,  1.97268352e-02,
        -1.27503229e-02,  1.16575370e-03, -3.26760225e-02,
         6.10489957e-02, -1.04520954e-02, -6.91033676e-02,
         3.60625982e-02,  4.39831913e-02, -1.22471740e-0

In [11]:
docs2 = ["The cat jumped over the dog"]

In [13]:
## this looks the same as the split_docs in the first 
split_docs2 = sorted(docs2[0].split(' '))
split_docs2

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [16]:
## but in this it looks very different from the first embeddings so the embeddings
## is perfect for comparison things...
embeddings2 = model.encode(docs2, clean_up_tokenization_spaces=False)
embeddings2

array([[ 4.72092964e-02,  3.36050391e-02,  6.90095127e-02,
         6.85966164e-02, -1.26861865e-02, -6.25294214e-03,
        -3.72542664e-02,  1.55752832e-02,  2.41127182e-02,
         2.21971446e-03,  7.17992187e-02,  2.92151365e-02,
         5.03156520e-03, -6.37696534e-02,  4.89638653e-03,
         1.07079523e-03, -1.23178720e-01,  9.51717794e-03,
         5.84048815e-02, -1.34705566e-02, -2.93737035e-02,
        -4.55944836e-02, -1.06726149e-02, -4.11552526e-02,
        -3.63232009e-02,  3.73865440e-02, -8.08678865e-02,
        -6.92620277e-02,  1.39805181e-02, -1.62780993e-02,
        -2.12400276e-02, -8.98963865e-03, -3.35779190e-02,
         5.97752631e-02, -6.10135794e-02, -7.63887390e-02,
         6.19942769e-02,  3.30317044e-03,  3.82678211e-02,
         1.23094998e-01, -3.98203023e-02,  7.74861174e-03,
        -1.22558232e-02, -2.10482627e-03, -3.81270647e-02,
         6.25126362e-02, -1.30796004e-02, -6.36048019e-02,
         3.17580514e-02,  5.67504503e-02, -1.24571035e-0

In [21]:
## we see here that the two embeddings are similar but 
model.similarity(embeddings2, embeddings2)

tensor([[1.0000]])

In [22]:
## in this we see the similarity is slite different
model.similarity(embeddings, embeddings2)

tensor([[0.9895]])